apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  ConnectionAzureEventHubs: STRING DE CONEXÃO DO AZURE EVENT HUBS EM BASE 64
  ConnectionAzureStorage: STRING DE CONEXÃO DO AZURE STORAGE EM BASE 64
  ConnectionSqlServer: STRING DE CONEXÃO DO SQL SERVER EM BASE 64
